### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ntromas** [BackofenLab/CRISPRidentify#3]
Hi,

First of all, thanks for this pipeline!
I used it on a multifasta file and I got a result folder for each contigs but I did not have the summary files.
Would be great to generate a summary of the results of all contigs (in 1 file) that would contain DR, spacer, start, end, type etc... Do you think it would be possible?

Cheers,
Nico

**Comment by Janeyzhen** [comment]
Cannot agree more!

**Comment by Alexander-Mitrofanov** [comment]
Thank you for the suggestion.
Will be added shortly.

**Comment by Janeyzhen** [comment]
Hi Alexander：

So sorry to bother you again, I have another problem when i was using the CRISPRidentify :

I have multiple files which contain multiline fasta sequences, i want to analysis these files with multithreading and when I was using the slurm array system to run CRISPRidentify over these inputs, it just couldn't run successfully. For example, when i set '#SBATCH --array=1-10' which the namelist contains 10 files' name, all but one were terminated in seconds after i submitted the job.sh. The error report is like this:

And I found that the CRISPRidentify directory would generate some intermediate files during its processing. So maybe the intermediate files were mistakenly deleted. I am so confused and have no idea, now I have to set the array just like this '#SBATCH --array=1-10%1' which it can only run one file in a 

loop...That's very inefficient.To solve this problem, I git cloned the CRISPRidentify to many different directories and created several different conda environments , but it is so awkward...




So could you help to improve this performance ? Thanks a lot !

Best,

Zhen

-----Original Messages-----

**Comment by Alexander-Mitrofanov** [comment]
I added the global summary for the submitted multifasta file.
We are about to integrate the classification of the array type and add it to the pipeline.
This info will also appear in the summary.

**Comment by ntromas** [comment]
Thanks!

Is there a way to be sure that the array is complete (leader and terminal seq?)? Are the spacers sequences added in the global summary?

Cheers

**Comment by Janeyzhen** [comment]
Hi, 

Yes, as I described in the previous letter, the script is just like this:

#!/bin/bash

#SBATCH --job-name=arc_split

#SBATCH --output=/share/home/jianglab/shared/refseq/archaea/genomic/genomic_fna/split/slurm.out/%x_%A_%a.out

#SBATCH --account=liuzhen

#SBATCH --partition=cpu

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=32

#SBATCH --time=14-00:00:0

#SBATCH --array=1-10

echo "SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

sample=$(head -n $SLURM_ARRAY_TASK_ID arcnamelist| tail -1)

echo $sample




inDir=/share/home/jianglab/shared/refseq/archaea/genomic/genomic_fna/split

python CRISPRidentify.py --input_folder $inDir/$sample --result_folder $inDir/crispridentity/$sample --fast_run True --cpu 32

 

and the "arcnamelist" is like this:

archaea.10.1.genomic.fna

archaea.1.1.genomic.fna
archaea.2.1.genomic.fna
archaea.3.1.genomic.fna
archaea.4.1.genomic.fna
archaea.5.1.genomic.fna
archaea.6.1.genomic.fna
archaea.7.1.genomic.fna
archaea.8.1.genomic.fna
archaea.9.1.genomic.fna

which represent 10 input folders, and each fold contains multiple contigs. However, it could not run in parallel.

and the python.py should run in the software's directory rather than other directory i want, and the generation and overwriting of intermediate files may result in the error. But running one by one is too slow while my task is a little urgent. So could you help me to solve this problem? 

Looking forward to hearing from you soon! 

-----Original Messages-----
From:ntromas ***@***.***>
Sent Time:2021-03-09 00:35:47 (Tuesday)
To: BackofenLab/CRISPRidentify ***@***.***>
Cc: Janeyzhen ***@***.***>, Comment ***@***.***>
Subject: Re: [BackofenLab/CRISPRidentify] Summary (#3)






Thanks!

Is there a way to be sure that the array is complete (leader and terminal seq?)?

**Comment by Alexander-Mitrofanov** [comment]
The current version of CRISPRidentify does not support the parallel run.
Since there is an obvious demand for this feature we will shortly update the tool.

**Comment by Janeyzhen** [comment]
Thanks!

Looking forward to the new version!



-----Original Messages-----
From:Alexander-Mitrofanov ***@***.***>
Sent Time:2021-03-16 23:08:29 (Tuesday)
To: BackofenLab/CRISPRidentify ***@***.***>
Cc: Janeyzhen ***@***.***>, Comment ***@***.***>
Subject: Re: [BackofenLab/CRISPRidentify] Summary (#3)






The current version of CRISPRidentify does not support the parallel run.
Since there is an obvious demand for this feature we will shortly update the tool.

**Comment by Janeyzhen** [comment]
Hoping and praying for the good news everyday!~

**Comment by Alexander-Mitrofanov** [comment]
The new release of the tool is available.
Metagenomic summaries are now created by the pipeline.
